### ISSUE TITLE
Question on single audio file inference.

### ISSUE THREAD

**Issue by tumbleintoyourheart** [Xflick/EEND_PyTorch#1]
Hi, 

First of all I want to give a thank to you for open-sourcing this work,

Secondly, does it support do inference on a single audio file?

**Comment by Xflick** [comment]
It does support a single .wav file inference. Though in the inference phase you need to specify a data_dir with a wav.scp file in that directory, your wav.scp file may contain only one audio file.

**Comment by tumbleintoyourheart** [comment]
Does it mean one can comments all the training part but the inferring+scoring then use the pretrained models with prepared wav.scp file containing the (list of?) test files?

**Comment by Xflick** [comment]
Yes. Or you may alternatively set stage=5 in run.sh file, which only does inferring and scoring. But I strongly recommend you split a little part of your test data to do adaptation, which may greatly boost the system performance.

**Comment by tumbleintoyourheart** [comment]
Thanks, I really appreciate such quick and informative responses.
