### ISSUE TITLE
Pretrained model on full training data

### ISSUE THREAD

**Issue by xiangzai0115** [Xflick/EEND_PyTorch#15]
Hi, 

Thanks for open-sourcing this work and providing the pretrained large model.

As you mentioned that your version missed the SwitchBoard Phase 1 for training data while your colleague got the one on full. I'm wondering the pretrained large in this repo is on full or without SwitchBoard Phase 1?

**Comment by Xflick** [comment]
It's trained on the missing data.

**Comment by xiangzai0115** [comment]
Okay, thanks!
Is that possible to open-source the pretrained large model on full set?

**Comment by Xflick** [comment]
The model trained on full-set data will not be open-sourced.
