### ISSUE TITLE
Speaker id assignment across chunks

### ISSUE THREAD

**Issue by xiangzai0115** [Xflick/EEND_PyTorch#16]
Hi,

Thanks again for open-sourcing the work and the response to my pretrained model issue before.

I do have a question: if the chunk size is smaller than the entire input length during inference which means we will get more than one chunk for one file, the speaker id across each chunk will not be consistent, right? because of the permutation. 
Just to confirm that you do not have any post processing when writing out rttm.

**Comment by Xflick** [comment]
![image](https://github.com/Xflick/EEND_PyTorch/assets/11536508/c3955b85-ae20-4563-8d1c-cdac9b24c413)
