### ISSUE TITLE
Question about the difference between Transformer implementation vs original architecture in the paper.

### ISSUE THREAD

**Issue by tumbleintoyourheart** [Xflick/EEND_PyTorch#2]
Hi,

In [End-to-End Neural Speaker Diarization with Self-attention](https://arxiv.org/abs/1909.06247)/**Fig. 2.**, LayerNorm was applied after the `Encoder block`s, but in [your implementation](https://github.com/Xflick/EEND_PyTorch/blob/69c0d8de9b54f0b5ab0fa96fc841de652a8173ab/eend/pytorch_backend/models.py#L103), the order was reversed. Are there any particular reasons for that?

Have a good day.

**Comment by Xflick** [comment]
Hi, actually my model implementation strictly follows the one in paper.

If you look into [PyTorch's TransformerEncoderLayer implementation](https://pytorch.org/docs/master/_modules/torch/nn/modules/transformer.html#TransformerEncoderLayer), you will find it is in the order: `self_attn->residual->norm->pointwise_ff->residual->norm`. However in _End-to-End Neural Speaker Diarization with Self-attention/Fig. 2_, the encoder block is defined as: `norm->self_attn->residual->norm->pointwise_ff->residual`, and with a layer_norm at the end (before linear+sigmoid).

Thus, applying layer_norm at the beginning in PyTorch code is equal to what they have done in their paper.

**Comment by tumbleintoyourheart** [comment]
Yeah, then everything makes sense. What a neat adaptation, thanks. Closing this now.
